### ISSUE TITLE
Author Email not present in Issue Details API

### ISSUE THREAD

**Issue by soniyash5000** [singh-yashwant/bugtracker-backend#2]
In the response of Issue Details API Author email was not present. Also i have aateched a Screenchot of it. Please see to it
![Screenshot from 2021-07-21 00-54-54](https://user-images.githubusercontent.com/61556252/126384053-7dec2d3b-ae0c-4103-927a-96a3b4a65849.png)

**Comment by singh-yashwant** [comment]
I have updated the /issues as well as /issue?index=x api to also return the 'author-email' key value pair. Refer the [documentation](https://documenter.getpostman.com/view/16075757/TzeZESKz#c14488b1-0338-4b4b-8ba1-7b5ffee3ad91) for request example
